// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPzLoWnX9F4MpdI_pCYEx_nF3mvGhMTz0',
    appId: '1:292905633005:web:cf7267134dc08413c038e4',
    messagingSenderId: '292905633005',
    projectId: 'flutterth-73a2e',
    authDomain: 'flutterth-73a2e.firebaseapp.com',
    storageBucket: 'flutterth-73a2e.firebasestorage.app',
    measurementId: 'G-QK1724MP5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrA20jI_5IuP7aECw6EExTZPG5ewiLcz0',
    appId: '1:292905633005:android:b0af7e6fea397065c038e4',
    messagingSenderId: '292905633005',
    projectId: 'flutterth-73a2e',
    storageBucket: 'flutterth-73a2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXx-qETUtnkBamqYMVREf-MBL4gBRMeGg',
    appId: '1:292905633005:ios:e44676500da9132ac038e4',
    messagingSenderId: '292905633005',
    projectId: 'flutterth-73a2e',
    storageBucket: 'flutterth-73a2e.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );
}
